crml: "1.1"
meta:
  name: "multinational-pii-compliance-risk"
  version: "1.0"
  description: |
    Multinational PII compliance risk model for a company operating in both
    the EU (Germany) and US (California).
    
    This model captures two distinct regulatory risks:
    - GDPR violations in Germany (fines in EUR)
    - CCPA violations in California (fines in USD)
    
    Use with --fx-config to normalize currencies for consolidated reporting:
      crml simulate multi-currency-example.yaml --fx-config fx-config.yaml
  author: "CRML Team"
  tags:
    - multi-currency
    - compliance
    - gdpr
    - ccpa
    - pii

# This model uses a mixture to represent two distinct regulatory risks
# Each component represents a different jurisdiction with its own currency

model:
  assets:
    description: "PII databases across EU and US operations"
    eu_databases: 45      # Customer databases in Germany
    us_databases: 120     # Customer databases in California
    cardinality: 165      # Total databases with PII

  frequency:
    model: poisson
    description: |
      Combined probability of a reportable PII breach across all jurisdictions.
      Based on industry data: ~3% of organizations experience a reportable breach annually.
    parameters:
      lambda: 0.03  # 3% annual probability per database

  severity:
    model: mixture
    description: |
      Mixture model representing fines from two regulatory regimes:
      - Component 1 (60%): GDPR fines in EUR (German DPA)
      - Component 2 (40%): CCPA fines in USD (California AG)
      
      Weights reflect the proportion of databases in each jurisdiction.
    components:
      # GDPR fines (Germany / EU)
      # German DPAs have issued fines ranging from €10K to €35M
      # Median fine for SME violations: ~€50K
      # For serious violations: €500K-€2M typical
      - lognormal:
          weight: 0.27        # 45/165 = ~27% of databases in EU
          median: "175 000"   # €175K median GDPR fine
          currency: EUR
          sigma: 1.8          # High variability (€10K to €20M range)
      
      # CCPA fines (California)
      # CCPA: $2,500 per unintentional violation, $7,500 per intentional
      # Typical settlements: $100K - $5M depending on records affected
      # California AG has been aggressive with enforcement since 2023
      - lognormal:
          weight: 0.73        # 120/165 = ~73% of databases in US
          median: "250 000"   # $250K median CCPA fine/settlement
          currency: USD
          sigma: 1.5          # Moderate variability

pipeline:
  simulation:
    monte_carlo:
      enabled: true
      runs: 10000
      description: "Monte Carlo simulation for annual loss estimation"

output:
  metrics:
    - EAL           # Expected Annual Loss (consolidated)
    - VaR_95        # 95th percentile loss
    - VaR_99        # 99th percentile loss
    - VaR_999       # 99.9th percentile (tail risk)
  distributions:
    annual_loss: true
  notes: |
    Results are displayed in the output currency specified in fx-config.
    For board reporting in EUR: use --fx-config fx-config-eur.yaml
    For board reporting in USD: use --fx-config fx-config-usd.yaml or the default (which is USD)
