#!/bin/bash

# CRML Wiki Publishing Script
# This script helps you publish wiki content to GitHub

echo "🚀 CRML Wiki Publishing Helper"
echo "================================"
echo ""
echo "GitHub wikis must be initialized through the web interface first."
echo ""
echo "📋 Steps to publish:"
echo ""
echo "1. Go to: https://github.com/Faux16/crml/wiki"
echo ""
echo "2. Click 'Create the first page' button"
echo ""
echo "3. For each page, copy content from the files below:"
echo ""
echo "   📄 Home page:"
echo "      File: wiki/Home.md"
echo "      URL: https://github.com/Faux16/crml/wiki/_new"
echo ""
echo "   📄 Roadmap page:"
echo "      File: wiki/Roadmap.md"
echo "      URL: https://github.com/Faux16/crml/wiki/Roadmap/_new"
echo ""
echo "   📄 Getting Started page:"
echo "      File: wiki/Getting-Started.md"
echo "      URL: https://github.com/Faux16/crml/wiki/Getting-Started/_new"
echo ""
echo "   📄 Control Effectiveness page:"
echo "      File: wiki/Control-Effectiveness.md"
echo "      URL: https://github.com/Faux16/crml/wiki/Control-Effectiveness/_new"
echo ""
echo "4. After creating the first page, you can clone the wiki repo:"
echo "   git clone https://github.com/Faux16/crml.wiki.git"
echo ""
echo "5. Then bulk upload remaining pages:"
echo "   cp -r wiki/* crml.wiki/"
echo "   cd crml.wiki"
echo "   git add ."
echo "   git commit -m 'Add comprehensive wiki content'"
echo "   git push origin master"
echo ""
echo "✅ All wiki files are ready in: $(pwd)/wiki/"
echo ""
echo "Would you like to open the wiki creation page? (y/n)"
