name: "Docs: Improvement"
description: "Suggest documentation improvements (new guides, clearer examples)."
title: "[docs][enhancement]: "
labels: ["enhancement", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Propose a documentation improvement.

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should the docs enable a reader to do?
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Proposed content
      description: Outline what you want added/changed.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Suggested location
      description: Where should this live?
      placeholder: "e.g. wiki/Guides/... or README section"

  - type: textarea
    id: extra
    attributes:
      label: Additional context
