crml: "1.1"
meta:
  name: "data-breach-simple"
  version: "1.0"
  description: "Simple data breach risk model for beginners"
  author: CRML Team
  tags:
    - data-breach
    - beginner
    - pii
  company_size:
    - smb
  industries:
    - all
  locale:
    regions: ["world"]
    countries: ["US"]
model:
  assets:
    - name: "database"
      cardinality: 50  # 50 databases with PII
  frequency:
    model: poisson
    parameters:
      lambda: 0.05  # 5% annual probability per database
  severity:
    model: lognormal
    parameters:
      median: "100 000"  # $100K median breach cost (ISO 80000-1 format)
      currency: USD
      sigma: 1.2  # Moderate variability
pipeline:
  simulation:
    monte_carlo:
      enabled: true
      runs: 10000
output:
  metrics:
    - EAL
    - VaR_95
    - VaR_99
  distributions:
    annual_loss: true
